// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollEngine.Web.Infrastructure.DataBase;

#nullable disable

namespace PayrollEngine.Web.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418134758_AddReducedIncomeTaxBase")]
    partial class AddReducedIncomeTaxBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.MinimumWage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredNetSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Params.DisabilityDegree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DisabilityDegrees");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Params.IncomeTaxBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bracket")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IncomeTaxBrackets");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Params.SSCeiling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ceiling")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SSCeilings");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Params.SSParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployeeUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActiveEmployerUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredEmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredEmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SSParams");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Params.StampTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StampTaxes");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.PayrollMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overtime_100_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime_50_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucher")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PayrollMonths");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.ResultPayroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativeIncomeTaxBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeSSContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeUIContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSSContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerUIContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTaxBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTaxExemption")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTaxRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime_100_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime_50_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReducedIncomeTaxBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SSContributionBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucherGrossAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucherIncomeTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucherNet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucherStampTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StampTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StampTaxExemption")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEmployerCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PayrollResults");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisabilityDegree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncentiveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
