// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollEngine.Web.Infrastructure.DataBase;

#nullable disable

namespace PayrollEngine.Web.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.MinimumWage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetiredNetSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.PayrollMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overtime_100_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime_50_Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucher")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PayrollMonths");
                });

            modelBuilder.Entity("PayrollEngine.Web.Domain.Entities.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisabilityDegree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncentiveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
